version: '3.8'

volumes:
  postgres_data_local:
    name: "thing_postgres_data"
  postgres_backup_local: 
    name: "thing_postgres_backup"

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app:Z
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    command: /start.sh
    networks:
      - thing
    ports:
      - "8000:8000"

  notebook:
    <<: *django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    environment:
        - DJANGO_ALLOW_ASYNC_UNSAFE=true
    ports:
      - "8888:8888"
    networks:
      - thing
    command: /start_notebook.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    volumes:
      - postgres_data_local:/var/lib/postgresql/data:Z
      - postgres_backup_local:/backups:Z
    env_file:
      - ./.envs/.postgres
    container_name: thing_postgres
    networks:
      - thing

networks:
  thing:
    name: thing
    ipam:
      driver: default
      config:
        - subnet: "172.42.0.1/24"
